<?php

namespace Database\Seeders;

use App\Models\Especialista;
use App\Models\Persona;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EspecialistaSeeder extends Seeder
{
    public function run(): void
    {
        $especialistas = [
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Carlos',
                'apellido'      => 'Mendoza Ríos',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Podología Clínica y Quirúrgica',
                'num_colegiado' => 'PM-0012',
                'telefono'      => '+507 6210-4455',
                'email'         => 'c.mendoza@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Sofía',
                'apellido'      => 'López Herrera',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Pie Diabético y Úlceras',
                'num_colegiado' => 'PM-0034',
                'telefono'      => '+507 6345-7821',
                'email'         => 's.lopez@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Roberto',
                'apellido'      => 'Vega Mora',
                'profesion'     => 'Fisioterapeuta',
                'especialidad'  => 'Biomecánica Podal y Ortopedia',
                'num_colegiado' => 'FT-0091',
                'telefono'      => '+507 6598-3310',
                'email'         => 'r.vega@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Carmen',
                'apellido'      => 'Díaz Pereira',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podología Deportiva',
                'num_colegiado' => 'PM-0057',
                'telefono'      => '+507 6712-9940',
                'email'         => 'c.diaz@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Téc. Esp.',
                'nombre'        => 'Andrés',
                'apellido'      => 'Castillo Núñez',
                'profesion'     => 'Técnico en Podología',
                'especialidad'  => 'Quiropodia y Cuidado Preventivo',
                'num_colegiado' => 'TP-0018',
                'telefono'      => '+507 6123-6677',
                'email'         => 'a.castillo@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Alejandra',
                'apellido'      => 'Ríos Figueroa',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podología Preventiva y Geriátrica',
                'num_colegiado' => 'PM-0073',
                'telefono'      => '+507 6301-2244',
                'email'         => 'a.rios@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Sebastián',
                'apellido'      => 'Núñez Barría',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Cirugía Ungueal y Patología de la Uña',
                'num_colegiado' => 'PM-0089',
                'telefono'      => '+507 6412-5533',
                'email'         => 's.nunez@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Paola',
                'apellido'      => 'Castañeda Vega',
                'profesion'     => 'Fisioterapeuta',
                'especialidad'  => 'Rehabilitación Podal y Terapia Manual',
                'num_colegiado' => 'FT-0115',
                'telefono'      => '+507 6534-6622',
                'email'         => 'p.castaneda@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Marcela',
                'apellido'      => 'Herrera Soto',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podopediatría y Pie Plano Infantil',
                'num_colegiado' => 'PM-0102',
                'telefono'      => '+507 6645-7711',
                'email'         => 'm.herrera@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Guillermo',
                'apellido'      => 'Peña Araúz',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Biomecánica Podal y Plantillas Ortopédicas',
                'num_colegiado' => 'PM-0118',
                'telefono'      => '+507 6756-8800',
                'email'         => 'g.pena@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Téc. Esp.',
                'nombre'        => 'María Isabel',
                'apellido'      => 'Ruiz Obando',
                'profesion'     => 'Técnica en Podología',
                'especialidad'  => 'Podología Estética y Onicocriptosis',
                'num_colegiado' => 'TP-0031',
                'telefono'      => '+507 6867-9944',
                'email'         => 'mi.ruiz@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Ramón',
                'apellido'      => 'Torres Quirós',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Pie Neuropático y Dermatología Podal',
                'num_colegiado' => 'PM-0135',
                'telefono'      => '+507 6978-1122',
                'email'         => 'r.torres@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Andrea',
                'apellido'      => 'Salas Moreno',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podología Oncológica y Pie Reumatoide',
                'num_colegiado' => 'PM-0147',
                'telefono'      => '+507 6089-3355',
                'email'         => 'a.salas@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Diego',
                'apellido'      => 'Espinoza Lara',
                'profesion'     => 'Técnico Ortopédico',
                'especialidad'  => 'Ortesis y Prótesis Podales',
                'num_colegiado' => 'OT-0022',
                'telefono'      => '+507 6190-4466',
                'email'         => 'd.espinoza@globalfeet.com',
            ],
            // ── 15 especialistas adicionales ─────────────────────────────────────
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Víctor',
                'apellido'      => 'Palma Jordán',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Podología Clínica General',
                'num_colegiado' => 'PM-0162',
                'telefono'      => '+507 6201-1234',
                'email'         => 'v.palma@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Camila',
                'apellido'      => 'Barría Ríos',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Onicomicosis y Patología Ungueal',
                'num_colegiado' => 'PM-0178',
                'telefono'      => '+507 6312-2345',
                'email'         => 'c.barria@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Héctor',
                'apellido'      => 'Vergara Pittí',
                'profesion'     => 'Fisioterapeuta',
                'especialidad'  => 'Electroterapia y Ultrasonido Podal',
                'num_colegiado' => 'FT-0134',
                'telefono'      => '+507 6423-3456',
                'email'         => 'h.vergara@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Isabella',
                'apellido'      => 'Moreno Aparicio',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Pie Plano y Hallux Valgus',
                'num_colegiado' => 'PM-0193',
                'telefono'      => '+507 6534-4567',
                'email'         => 'i.moreno@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Nicolás',
                'apellido'      => 'Guerrero Samaniego',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Cirugía Podológica Mínimamente Invasiva',
                'num_colegiado' => 'PM-0207',
                'telefono'      => '+507 6645-5678',
                'email'         => 'n.guerrero@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Téc. Esp.',
                'nombre'        => 'Fernanda',
                'apellido'      => 'Quirós Batista',
                'profesion'     => 'Técnica en Podología',
                'especialidad'  => 'Quiropodia Avanzada y Nail Art Terapéutico',
                'num_colegiado' => 'TP-0049',
                'telefono'      => '+507 6756-6789',
                'email'         => 'f.quiros@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Eduardo',
                'apellido'      => 'Muñoz Cisneros',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Dermatología Podológica',
                'num_colegiado' => 'PM-0221',
                'telefono'      => '+507 6867-7890',
                'email'         => 'e.munoz@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Valentina',
                'apellido'      => 'Solis Brathwaite',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podología Geriátrica y Paliativa',
                'num_colegiado' => 'PM-0235',
                'telefono'      => '+507 6978-8901',
                'email'         => 'v.solis@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Sebastián',
                'apellido'      => 'Chávez Obaldia',
                'profesion'     => 'Técnico Ortopédico',
                'especialidad'  => 'Plantillas Termoformadas y Biomecánica',
                'num_colegiado' => 'OT-0038',
                'telefono'      => '+507 6089-9012',
                'email'         => 's.chavez@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Mariela',
                'apellido'      => 'Ureña Pittí',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Pie Diabético Avanzado y Amputaciones',
                'num_colegiado' => 'PM-0249',
                'telefono'      => '+507 6190-0123',
                'email'         => 'm.urena@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dr.',
                'nombre'        => 'Alfredo',
                'apellido'      => 'Castillo De León',
                'profesion'     => 'Podólogo',
                'especialidad'  => 'Podología Deportiva de Alto Rendimiento',
                'num_colegiado' => 'PM-0263',
                'telefono'      => '+507 6301-1234',
                'email'         => 'a.castillo2@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Rebeca',
                'apellido'      => 'Jaramillo Vásquez',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podopediatría y Desarrollo del Pie Infantil',
                'num_colegiado' => 'PM-0277',
                'telefono'      => '+507 6412-2345',
                'email'         => 'r.jaramillo@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Lic.',
                'nombre'        => 'Gustavo',
                'apellido'      => 'Lezcano Herrera',
                'profesion'     => 'Fisioterapeuta',
                'especialidad'  => 'Kinesiotaping y Vendaje Funcional Podal',
                'num_colegiado' => 'FT-0158',
                'telefono'      => '+507 6523-3456',
                'email'         => 'g.lezcano@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Dra.',
                'nombre'        => 'Priscila',
                'apellido'      => 'Araúz Espinoza',
                'profesion'     => 'Podóloga',
                'especialidad'  => 'Podología Oncológica y Cuidado Paliativo',
                'num_colegiado' => 'PM-0291',
                'telefono'      => '+507 6634-4567',
                'email'         => 'p.arauz@globalfeet.com',
            ],
            [
                'tratamiento'   => 'Téc. Esp.',
                'nombre'        => 'Wilmer',
                'apellido'      => 'Rodríguez Batista',
                'profesion'     => 'Técnico en Podología',
                'especialidad'  => 'Podología Estética y Reconstrucción Ungueal',
                'num_colegiado' => 'TP-0062',
                'telefono'      => '+507 6745-5678',
                'email'         => 'w.rodriguez@globalfeet.com',
            ],
        ];

        foreach ($especialistas as $data) {
            DB::transaction(function () use ($data) {
                // Verificar si ya existe por email
                if (Especialista::whereHas('persona', fn($q) => $q->where('email', $data['email']))->exists()) {
                    return;
                }

                $persona = Persona::create([
                    'nombre'             => $data['nombre'],
                    'apellido'           => $data['apellido'],
                    'tipo_identificacion' => 'N/A',
                    'identificacion'     => 'N/A',
                    'contacto'           => $data['telefono'],
                    'email'              => $data['email'],
                    'estado'             => true,
                ]);

                Especialista::create([
                    'persona_id'    => $persona->id,
                    'tratamiento'   => $data['tratamiento'],
                    'profesion'     => $data['profesion'],
                    'especialidad'  => $data['especialidad'],
                    'num_colegiado' => $data['num_colegiado'],
                    'telefono'      => $data['telefono'],
                    'email'         => $data['email'],
                    'estado'        => true,
                ]);
            });
        }
    }
}
